<div align="center">

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.png)](https://colab.research.google.com/github/wisaaco/Curs_FG24GOI0074221/blob/main/lessons/projecte_final.ipynb)

Si no funciona el botó podeu copiar el següent [enllaç](https://colab.research.google.com/github/wisaaco/Curs_FG24GOI0074221/blob/main/lessons/projecte_final.ipynb)

</div>

# Projecte final

Enllaç a les dades [aquí](https://github.com/wisaaco/Curs_FG24GOI0074221/blob/main/lessons/data/data_certificats.csv)

Les qüestions plantejades en aquest projecte final aprofiten les eines i mecanismes treballats durant el curs per dur a terme el tractament i l'anàlisi de dades amb Python.

Les activitats es classifiquen en tres nivells segons el seu grau de complexitat. Els tres nivells us serviran com a autoavaluació. El projecte es considerarà completat si, com a mínim, supereu les qüestions plantejades en el primer nivell. Els tres nivells són: bàsic, intermedi i avançat.

Es valorarà:

- El mínim ús d'estructures de control de codi (if, for, while, etc.), prioritzant l'ús dels mètodes de Pandas.
- La inclusió de gràfics per mostrar els resultats de les qüestions.
- L'explicació clara de les accions realitzades mitjançant l'ús de Markdown entre les cel·les de codi.

## Nivell bàsic

In [ ]:
# Dades 
import pandas as pd

df = pd.read_csv("data/data_certificats.csv")
df.head(5)

In [ ]:
# 1.1 Selecciona les dades de les 10 primeres persones amb el salari més alt

In [ ]:
# 1.2 Fes una nova columna amb un increment del salari del 2%

In [ ]:
# 1.3 Selecciona les persones de "Ariany", 
# - quantes hi ha?
# - quin percentatge representen amb respecte el total?

In [ ]:
# 1.4 Quina es la mitja de punts de Palma?

In [ ]:
# 1.5 Quin o quines són les persones amb més punts?

In [ ]:
# 1.6 Amb la llibrería Seaborm, fes una figura de barres dels "Punts" (y) per tipus de "Sexe" (hue) i agrupats per "Tipus de certificat cat" (x)

In [ ]:
# 1.7 Fes el mateix (1.6), però amb els valors de "Tipus certificat cat" ordenats (A,B,C,D)

In [ ]:
# 1.8 Amb la llibrería Seaborn, fes un violinplot del Salari (y), per a cada "Tipus certificat cat" (x) i diferènciant el Sexe (hue)

In [ ]:
# 1.9 Amb la llibreria Seaborn, fes un barplot de les Ciutats i els Salaris associats.
# - No mostris l'errorbar.
# - Assegura't que les etiquetes de les Ciutats no es sobreposin.

## Nivell intermedi

Les activitats d'aquest nivell estan dissenyades per mostrar-vos el cost que suposa l'anàlisi de dades a causa d'una mala pràctica en la publicació de dades.

L'objectiu de totes aquestes tasques serà simplement visualitzar la despesa total que realitzen els turistes a la nostra comunitat. Com podeu veure en la següent imatge:

<img src="images/resultat_projecte_final.png" width="20%">

Donada la relativa complexitat d'algunes instruccions, seran activitats guiades, i hi haurà cel·les que haureu de completar

Treballarem amb el document: "Gasto de los turistas extranjeros por periodo y Comunidad Autónoma de destino principal" (Font: IBESTAT).

El fitxer està disponible al repositori i també a la seva pàgina web (descarregar la versió CSV):
https://intranet.caib.es/ibestat-jaxi/tabla.do?px=68904221-f893-456c-8046-261150ba9a2e&pag=1&nodeId=%20f58f0937-c64f-469d-bad5-99f29bbb59ce%20&pxName=I208004_n100.px

**Primer detall**: no és recomanable utilitzar noms de fitxers amb espais o accents.
Abans de carregar el document, haurem de comprovar el separador, el format de representació de caràcters i altres detalls, com la posició dels noms de les columnes.

In [5]:
import pandas as pd
import numpy as np
df = pd.read_csv("data/IBESTAT_Gasto de los turistas extranjeros por periodo y Comunidad Autónoma de destino principal.csv",sep=";",header=1) # Comproveu el path
df.head(13)

,Unnamed: 0,Gasto total (millones de euros),Gasto por persona (euros),Gasto por persona y día (euros),Gasto total (millones de euros).1,Gasto por persona (euros).1,Gasto por persona y día (euros).1,Gasto total (millones de euros).2,Gasto por persona (euros).2,Gasto por persona y día (euros).2,Gasto total (millones de euros).3,Gasto por persona (euros).3,Gasto por persona y día (euros).3,Unnamed: 13
0,2024M07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TOTAL,"15,534,68","1,432,00",195.0,11.91,4.34,2.11,"71,108,37","1,332,00",187.0,18.59,5.88,4.42,NaN
2,Andalucia,"2,033,87","1,391,00",169.0,10.30,1.49,1.94,"10,306,32","1,333,00",163.0,22.53,8.46,7.51,NaN
3,Illes Balears,"3,784,18","1,488,00",220.0,16.21,11.40,4.66,"11,110,75","1,275,00",206.0,14.60,7.14,6.72,NaN
4,Canarias,"1,947,43","1,677,00",207.0,4.98,-3.20,5.91,"13,025,05","1,497,00",180.0,14.47,3.75,6.96,NaN
5,Cataluña,"3,127,32","1,306,00",220.0,2.09,-1.56,-0.74,"13,438,18","1,172,00",218.0,12.94,2.23,1.80,NaN
6,Comunidad Valenciana,"2,062,59","1,397,00",139.0,20.11,8.38,-0.03,"8,499,00","1,252,00",132.0,25.90,6.86,1.63,NaN
7,Madrid (Comunidad de),"1,424,35","1,915,00",317.0,17.23,4.75,6.39,"9,496,25","1,833,00",303.0,27.62,7.13,1.89,NaN
8,Resto CCAA,"1,154,94","1,078,00",157.0,24.20,11.11,5.06,"5,232,82","1,090,00",154.0,19.38,6.80,3.54,NaN
9,2024M06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,TOTAL,"12,373,28","1,329,00",196.0,16.64,4.04,1.89,"55,573,70","1,307,00",185.0,20.61,6.46,5.18,NaN
11,Andalucia,"1,748,41","1,280,00",169.0,22.73,3.86,0.09,"8,272,45","1,319,00",162.0,25.96,10.47,9.14,NaN
12,Illes Balears,"2,753,18","1,254,00",208.0,12.59,5.56,5.78,"7,326,57","1,187,00",199.0,13.79,5.26,7.59,NaN

Si volem representar temporalment la despesa sobre les Illes, hem de treballar amb una columna que conté dos tipus d'informació diferents.

**Segon problema**: estructuració inadequada del document CSV. Per què es barregen columnes? Per maquetació? Malament.

Haurem de fer diversos passos per separar aquesta informació, convertir certs valors a format de temps (2024-01, 2024-02, etc.) i altres a Comunitats Autònomes. Necessitem el "TOTAL"? No

In [6]:
dates = df[df.columns[0]].apply(lambda x: x if x[0].isdigit() else np.nan)
print(dates[:14])

0     2024M07
1         NaN
2         NaN
3         NaN
4         NaN
5         NaN
6         NaN
7         NaN
8         NaN
9     2024M06
10        NaN
11        NaN
12        NaN
13        NaN
Name: Unnamed: 0, dtype: object

In [7]:
dates.fillna(method="ffill",inplace=True) # Què fem amb aquesta instrucció?
print(dates[:14])

0     2024M07
1     2024M07
2     2024M07
3     2024M07
4     2024M07
5     2024M07
6     2024M07
7     2024M07
8     2024M07
9     2024M06
10    2024M06
11    2024M06
12    2024M06
13    2024M06
Name: Unnamed: 0, dtype: object

In [8]:
dates_ok = pd.to_datetime(dates.str.replace('M', '-', regex = True), format = '%Y-%m') # Què fem amb aquesta instrucció?
print(dates_ok[:14])

0    2024-07-01
1    2024-07-01
2    2024-07-01
3    2024-07-01
4    2024-07-01
5    2024-07-01
6    2024-07-01
7    2024-07-01
8    2024-07-01
9    2024-06-01
10   2024-06-01
11   2024-06-01
12   2024-06-01
13   2024-06-01
Name: Unnamed: 0, dtype: datetime64[ns]

In [9]:
df.index = pd.to_datetime(dates_ok) # Què fem amb aquesta instrucció?
df.head(13)

,Unnamed: 0,Gasto total (millones de euros),Gasto por persona (euros),Gasto por persona y día (euros),Gasto total (millones de euros).1,Gasto por persona (euros).1,Gasto por persona y día (euros).1,Gasto total (millones de euros).2,Gasto por persona (euros).2,Gasto por persona y día (euros).2,Gasto total (millones de euros).3,Gasto por persona (euros).3,Gasto por persona y día (euros).3,Unnamed: 13
Unnamed: 0,,,,,,,,,,,,,,
2024-07-01,2024M07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-07-01,TOTAL,"15,534,68","1,432,00",195.0,11.91,4.34,2.11,"71,108,37","1,332,00",187.0,18.59,5.88,4.42,NaN
2024-07-01,Andalucia,"2,033,87","1,391,00",169.0,10.30,1.49,1.94,"10,306,32","1,333,00",163.0,22.53,8.46,7.51,NaN
2024-07-01,Illes Balears,"3,784,18","1,488,00",220.0,16.21,11.40,4.66,"11,110,75","1,275,00",206.0,14.60,7.14,6.72,NaN
2024-07-01,Canarias,"1,947,43","1,677,00",207.0,4.98,-3.20,5.91,"13,025,05","1,497,00",180.0,14.47,3.75,6.96,NaN
2024-07-01,Cataluña,"3,127,32","1,306,00",220.0,2.09,-1.56,-0.74,"13,438,18","1,172,00",218.0,12.94,2.23,1.80,NaN
2024-07-01,Comunidad Valenciana,"2,062,59","1,397,00",139.0,20.11,8.38,-0.03,"8,499,00","1,252,00",132.0,25.90,6.86,1.63,NaN
2024-07-01,Madrid (Comunidad de),"1,424,35","1,915,00",317.0,17.23,4.75,6.39,"9,496,25","1,833,00",303.0,27.62,7.13,1.89,NaN
2024-07-01,Resto CCAA,"1,154,94","1,078,00",157.0,24.20,11.11,5.06,"5,232,82","1,090,00",154.0,19.38,6.80,3.54,NaN
2024-06-01,2024M06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-06-01,TOTAL,"12,373,28","1,329,00",196.0,16.64,4.04,1.89,"55,573,70","1,307,00",185.0,20.61,6.46,5.18,NaN
2024-06-01,Andalucia,"1,748,41","1,280,00",169.0,22.73,3.86,0.09,"8,272,45","1,319,00",162.0,25.96,10.47,9.14,NaN
2024-06-01,Illes Balears,"2,753,18","1,254,00",208.0,12.59,5.56,5.78,"7,326,57","1,187,00",199.0,13.79,5.26,7.59,NaN

Segona tasca, crear una nova columna amb les comunitats.

In [11]:
comunidades = df[df.columns[0]].apply(lambda x: x if (not x[0].isdigit()) and x != '   TOTAL' else np.nan)
comunidades.head(13)

Unnamed: 0
2024-07-01                         NaN
2024-07-01                         NaN
2024-07-01                   Andalucia
2024-07-01               Illes Balears
2024-07-01                    Canarias
2024-07-01                    Cataluña
2024-07-01        Comunidad Valenciana
2024-07-01       Madrid (Comunidad de)
2024-07-01                  Resto CCAA
2024-06-01                         NaN
2024-06-01                         NaN
2024-06-01                   Andalucia
2024-06-01               Illes Balears
Name: Unnamed: 0, dtype: object

In [12]:
# TODO: Crea al DF una nova columna "Comunidades" amb el valors d'aquesta serie
df["Comunidades"] = #TODO
df.head(13)

,Unnamed: 0,Gasto total (millones de euros),Gasto por persona (euros),Gasto por persona y día (euros),Gasto total (millones de euros).1,Gasto por persona (euros).1,Gasto por persona y día (euros).1,Gasto total (millones de euros).2,Gasto por persona (euros).2,Gasto por persona y día (euros).2,Gasto total (millones de euros).3,Gasto por persona (euros).3,Gasto por persona y día (euros).3,Unnamed: 13,Comunidades
Unnamed: 0,,,,,,,,,,,,,,,
2024-07-01,2024M07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-07-01,TOTAL,"15,534,68","1,432,00",195.0,11.91,4.34,2.11,"71,108,37","1,332,00",187.0,18.59,5.88,4.42,NaN,NaN
2024-07-01,Andalucia,"2,033,87","1,391,00",169.0,10.30,1.49,1.94,"10,306,32","1,333,00",163.0,22.53,8.46,7.51,NaN,Andalucia
2024-07-01,Illes Balears,"3,784,18","1,488,00",220.0,16.21,11.40,4.66,"11,110,75","1,275,00",206.0,14.60,7.14,6.72,NaN,Illes Balears
2024-07-01,Canarias,"1,947,43","1,677,00",207.0,4.98,-3.20,5.91,"13,025,05","1,497,00",180.0,14.47,3.75,6.96,NaN,Canarias
2024-07-01,Cataluña,"3,127,32","1,306,00",220.0,2.09,-1.56,-0.74,"13,438,18","1,172,00",218.0,12.94,2.23,1.80,NaN,Cataluña
2024-07-01,Comunidad Valenciana,"2,062,59","1,397,00",139.0,20.11,8.38,-0.03,"8,499,00","1,252,00",132.0,25.90,6.86,1.63,NaN,Comunidad Valenciana
2024-07-01,Madrid (Comunidad de),"1,424,35","1,915,00",317.0,17.23,4.75,6.39,"9,496,25","1,833,00",303.0,27.62,7.13,1.89,NaN,Madrid (Comunidad de)
2024-07-01,Resto CCAA,"1,154,94","1,078,00",157.0,24.20,11.11,5.06,"5,232,82","1,090,00",154.0,19.38,6.80,3.54,NaN,Resto CCAA
2024-06-01,2024M06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-06-01,TOTAL,"12,373,28","1,329,00",196.0,16.64,4.04,1.89,"55,573,70","1,307,00",185.0,20.61,6.46,5.18,NaN,NaN
2024-06-01,Andalucia,"1,748,41","1,280,00",169.0,22.73,3.86,0.09,"8,272,45","1,319,00",162.0,25.96,10.47,9.14,NaN,Andalucia
2024-06-01,Illes Balears,"2,753,18","1,254,00",208.0,12.59,5.56,5.78,"7,326,57","1,187,00",199.0,13.79,5.26,7.59,NaN,Illes Balears

In [13]:
# Borrant columnes innecesaries: "Unnamed: 0", "Unnamed: 13"
df.drop(['Unnamed: 0',"Unnamed: 13"], axis=1,inplace=True)

In [14]:
# TODO: Borra totes les files (que no tenen comunitat: per Total o por data)
df = #TODO

In [15]:
df.head(13)

,Gasto total (millones de euros),Gasto por persona (euros),Gasto por persona y día (euros),Gasto total (millones de euros).1,Gasto por persona (euros).1,Gasto por persona y día (euros).1,Gasto total (millones de euros).2,Gasto por persona (euros).2,Gasto por persona y día (euros).2,Gasto total (millones de euros).3,Gasto por persona (euros).3,Gasto por persona y día (euros).3,Comunidades
Unnamed: 0,,,,,,,,,,,,,
2024-07-01,"2,033,87","1,391,00",169.0,10.30,1.49,1.94,"10,306,32","1,333,00",163.0,22.53,8.46,7.51,Andalucia
2024-07-01,"3,784,18","1,488,00",220.0,16.21,11.40,4.66,"11,110,75","1,275,00",206.0,14.60,7.14,6.72,Illes Balears
2024-07-01,"1,947,43","1,677,00",207.0,4.98,-3.20,5.91,"13,025,05","1,497,00",180.0,14.47,3.75,6.96,Canarias
2024-07-01,"3,127,32","1,306,00",220.0,2.09,-1.56,-0.74,"13,438,18","1,172,00",218.0,12.94,2.23,1.80,Cataluña
2024-07-01,"2,062,59","1,397,00",139.0,20.11,8.38,-0.03,"8,499,00","1,252,00",132.0,25.90,6.86,1.63,Comunidad Valenciana
2024-07-01,"1,424,35","1,915,00",317.0,17.23,4.75,6.39,"9,496,25","1,833,00",303.0,27.62,7.13,1.89,Madrid (Comunidad de)
2024-07-01,"1,154,94","1,078,00",157.0,24.20,11.11,5.06,"5,232,82","1,090,00",154.0,19.38,6.80,3.54,Resto CCAA
2024-06-01,"1,748,41","1,280,00",169.0,22.73,3.86,0.09,"8,272,45","1,319,00",162.0,25.96,10.47,9.14,Andalucia
2024-06-01,"2,753,18","1,254,00",208.0,12.59,5.56,5.78,"7,326,57","1,187,00",199.0,13.79,5.26,7.59,Illes Balears
2024-06-01,"1,439,08","1,376,00",190.0,12.65,2.12,7.39,"11,077,62","1,469,00",176.0,16.31,5.14,7.39,Canarias
2024-06-01,"2,531,26","1,263,00",248.0,12.85,2.48,0.53,"10,310,86","1,137,00",218.0,16.70,3.81,2.71,Cataluña
2024-06-01,"1,403,11","1,253,00",132.0,26.32,5.70,2.69,"6,436,42","1,212,00",130.0,27.87,6.63,2.26,Comunidad Valenciana
2024-06-01,"1,606,18","1,902,00",298.0,20.91,6.71,1.27,"8,071,89","1,819,00",301.0,29.65,7.65,1.13,Madrid (Comunidad de)

Moltes vegades es guarden les dades sense seguir un estàndard, i passa el que passa... Fixeu-vos: les comes per separar milers i cèntims a la columna "Gasto total (millones de euros)". Malament.

In [16]:
serieTMP = df['Gasto total (millones de euros)'].str.replace(",","",1) #què farà el 1 del replace?
serieTMP

Unnamed: 0
2024-07-01    2033,87
2024-07-01    3784,18
2024-07-01    1947,43
2024-07-01    3127,32
2024-07-01    2062,59
               ...
2016-01-01    1272,47
2016-01-01     830.87
2016-01-01     308.13
2016-01-01     465.09
2016-01-01     255.58
Name: Gasto total (millones de euros), Length: 721, dtype: object

In [17]:
serieTMP = serieTMP.str.replace(",",".",1)
serieTMP

Unnamed: 0
2024-07-01    2033.87
2024-07-01    3784.18
2024-07-01    1947.43
2024-07-01    3127.32
2024-07-01    2062.59
               ...
2016-01-01    1272.47
2016-01-01     830.87
2016-01-01     308.13
2016-01-01     465.09
2016-01-01     255.58
Name: Gasto total (millones de euros), Length: 721, dtype: object

In [19]:
df['Gasto total (millones de euros)'] = serieTMP.astype(float)
df.head(13)

,Gasto total (millones de euros),Gasto por persona (euros),Gasto por persona y día (euros),Gasto total (millones de euros).1,Gasto por persona (euros).1,Gasto por persona y día (euros).1,Gasto total (millones de euros).2,Gasto por persona (euros).2,Gasto por persona y día (euros).2,Gasto total (millones de euros).3,Gasto por persona (euros).3,Gasto por persona y día (euros).3,Comunidades
Unnamed: 0,,,,,,,,,,,,,
2024-07-01,2033.87,"1,391,00",169.0,10.30,1.49,1.94,"10,306,32","1,333,00",163.0,22.53,8.46,7.51,Andalucia
2024-07-01,3784.18,"1,488,00",220.0,16.21,11.40,4.66,"11,110,75","1,275,00",206.0,14.60,7.14,6.72,Illes Balears
2024-07-01,1947.43,"1,677,00",207.0,4.98,-3.20,5.91,"13,025,05","1,497,00",180.0,14.47,3.75,6.96,Canarias
2024-07-01,3127.32,"1,306,00",220.0,2.09,-1.56,-0.74,"13,438,18","1,172,00",218.0,12.94,2.23,1.80,Cataluña
2024-07-01,2062.59,"1,397,00",139.0,20.11,8.38,-0.03,"8,499,00","1,252,00",132.0,25.90,6.86,1.63,Comunidad Valenciana
2024-07-01,1424.35,"1,915,00",317.0,17.23,4.75,6.39,"9,496,25","1,833,00",303.0,27.62,7.13,1.89,Madrid (Comunidad de)
2024-07-01,1154.94,"1,078,00",157.0,24.20,11.11,5.06,"5,232,82","1,090,00",154.0,19.38,6.80,3.54,Resto CCAA
2024-06-01,1748.41,"1,280,00",169.0,22.73,3.86,0.09,"8,272,45","1,319,00",162.0,25.96,10.47,9.14,Andalucia
2024-06-01,2753.18,"1,254,00",208.0,12.59,5.56,5.78,"7,326,57","1,187,00",199.0,13.79,5.26,7.59,Illes Balears
2024-06-01,1439.08,"1,376,00",190.0,12.65,2.12,7.39,"11,077,62","1,469,00",176.0,16.31,5.14,7.39,Canarias
2024-06-01,2531.26,"1,263,00",248.0,12.85,2.48,0.53,"10,310,86","1,137,00",218.0,16.70,3.81,2.71,Cataluña
2024-06-01,1403.11,"1,253,00",132.0,26.32,5.70,2.69,"6,436,42","1,212,00",130.0,27.87,6.63,2.26,Comunidad Valenciana
2024-06-01,1606.18,"1,902,00",298.0,20.91,6.71,1.27,"8,071,89","1,819,00",301.0,29.65,7.65,1.13,Madrid (Comunidad de)

Arriba el moment de fer la gràfica, però... un altre detall inadequat.
Si pretenem seleccionar la comunitat de "Illes Balears", haurem de revisar el format de la cadena de text.

Fixeu-vos en el següent detall amb aquesta instrucció: realment no tindrem "Andalucia" sinó "   Andalusia"!!! MALAMENT.

In [10]:
np.unique(df[df.columns[0]])

array(['   Andalucia', '   Canarias', '   Cataluña',
       '   Comunidad Valenciana', '   Illes Balears',
       '   Madrid (Comunidad de)', '   Resto CCAA', '   TOTAL', '2016M01',
       '2016M02', '2016M03', '2016M04', '2016M05', '2016M06', '2016M07',
       '2016M08', '2016M09', '2016M10', '2016M11', '2016M12', '2017M01',
       '2017M02', '2017M03', '2017M04', '2017M05', '2017M06', '2017M07',
       '2017M08', '2017M09', '2017M10', '2017M11', '2017M12', '2018M01',
       '2018M02', '2018M03', '2018M04', '2018M05', '2018M06', '2018M07',
       '2018M08', '2018M09', '2018M10', '2018M11', '2018M12', '2019M01',
       '2019M02', '2019M03', '2019M04', '2019M05', '2019M06', '2019M07',
       '2019M08', '2019M09', '2019M10', '2019M11', '2019M12', '2020M01',
       '2020M02', '2020M03', '2020M04', '2020M05', '2020M06', '2020M07',
       '2020M08', '2020M09', '2020M10', '2020M11', '2020M12', '2021M01',
       '2021M02', '2021M03', '2021M04', '2021M05', '2021M06', '2021M07',
       '2021M08', '2021M09', '2021M10', '2021M11', '2021M12', '2022M01',
       '2022M02', '2022M03', '2022M04', '2022M05', '2022M06', '2022M07',
       '2022M08', '2022M09', '2022M10', '2022M11', '2022M12', '2023M01',
       '2023M02', '2023M03', '2023M04', '2023M05', '2023M06', '2023M07',
       '2023M08', '2023M09', '2023M10', '2023M11', '2023M12', '2024M01',
       '2024M02', '2024M03', '2024M04', '2024M05', '2024M06', '2024M07'],
      dtype=object)

In [23]:
### Crea un lineplot de seaborn amb les dates (x = index.year ) i  y = 'Gasto total (millones de euros)') d'aquest dataframe dfIB
import seaborn as sns
dfIB = df[df.Comunidades=='   Illes Balears']
dfIB.head()
#TODO gràfic
# En aquest gràfic pots veure com ha afectat la pandèmia?

,Gasto total (millones de euros),Gasto por persona (euros),Gasto por persona y día (euros),Gasto total (millones de euros).1,Gasto por persona (euros).1,Gasto por persona y día (euros).1,Gasto total (millones de euros).2,Gasto por persona (euros).2,Gasto por persona y día (euros).2,Gasto total (millones de euros).3,Gasto por persona (euros).3,Gasto por persona y día (euros).3,Comunidades
Unnamed: 0,,,,,,,,,,,,,
2024-07-01,3784.18,"1,488,00",220.0,16.21,11.40,4.66,"11,110,75","1,275,00",206.0,14.60,7.14,6.72,Illes Balears
2024-06-01,2753.18,"1,254,00",208.0,12.59,5.56,5.78,"7,326,57","1,187,00",199.0,13.79,5.26,7.59,Illes Balears
2024-05-01,2219.84,"1,111,00",212.0,16.62,4.95,8.79,"4,573,39","1,150,00",194.0,14.52,5.15,8.68,Illes Balears
2024-04-01,1393.72,"1,165,00",190.0,4.96,3.77,5.72,"2,353,55","1,190,00",180.0,12.60,5.47,8.32,Illes Balears
2024-03-01,525.62,"1,227,00",179.0,20.99,1.94,17.10,959.83,"1,227,00",167.0,25.90,7.93,13.85,Illes Balears

## Nivell avançat

A partir del fitxer: 
- https://datos.gob.es/en/catalogo/a04003003-periodo-medio-de-pago-a-proveedores-de-la-comunidad-autonoma-de-las-illes-balears

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("Periode_Mitj__de_Pagament__PMP__a_prove_dors_de_la_Comunitat_Aut_noma_de_les_Illes_Balears.csv")
df.index = pd.to_datetime(df['Data']) # sèrie temporal al index.

print(df.head())
print(df.loc["2020"].head(3))

In [ ]:
# 3.1 Llista els àmbits disponibles

In [ ]:
# 3.2 Cuantes entitats diferents hi ha?

In [ ]:
# 3.3 Quin periode abarca els pagaments a la UIB? (data min i max)

In [2]:
# 3.4 Crea una gràfica amb seaborn de línies amb el 'Període Mitjà de Pagament (PMP)' dels valors de la UIB

In [ ]:
# 3.5 Crea un dataframe agrupant els Àmbits i treu la suma de 'Pagaments realitzats (milers d'euros)'

In [ ]:
# 3.6 El mateix, però només del 2020

In [ ]:
# 3.7 Visualitza amb un lineplot (de seaborn) l'agrupació dels valors per Àmbit i Any, i treu la suma de 'Pagaments realitzats (milers d'euros)'

[![License: CC BY 4.0](https://img.shields.io/badge/License-CC_BY_4.0-lightgrey.svg)](https://creativecommons.org/licenses/by/4.0/) <br/>
Isaac Lera and Gabriel Moya <br/>
Universitat de les Illes Balears <br/>
isaac.lera@uib.edu, gabriel.moya@uib.edu